### ISSUE TITLE
Autenticação + Token

### ISSUE THREAD

**Issue by sotnaspina** [alexfelipe/ceep-post-collabcode#1]
Fala aí mestre!!

Aqui, teria algum material baseado no que vc fez aqui, mas, com a parte de autenticação para passar o token (Authorization Bearer...) no header das requisições?

Grato!

**Comment by alexfelipe** [comment]
Opa Sotnas, tudo bem?

Eu ainda não fiz nenhum conteúdo ou disponibilizei um projeto com essa feature, mas acredito que dê pra fazer com pesquisas em documentação ou conteúdos em Inglês :)

Só mais um detalhe, a página de issues é mais usada para problemas ou solicitações do projeto, sendo assim, quando for dúvidas do gênero, pode mandar diretamente nos artigos por favor? Por exemplo, [neste artigo que agrego meus conteúdos de Kotlin](https://medium.com/collabcode/seja-tamb%C3%A9m-um-desenvolvedor-kotlin-770188949486).
